# Generated by Django 5.2.7 on 2025-10-07 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('expertise', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
